apiVersion: apps/v1
kind: Deployment
metadata:
  name: pingpong-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pingpong
  template:
    metadata:
      labels:
        app: pingpong
    spec:
      containers:
        - name: pingpong
          image: ethanrailo/pingpong:version1.31
          env:
            - name: PYTHONUNBUFFERED
              value: "1"
            - name: PORT
              value: "3000"
            - name: PSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: dwk-exercises-postgres-password
                  key: PSQL_PASSWORD
          envFrom:
            - configMapRef:
                name: pingpong-configmap
