apiVersion: apps/v1
kind: Deployment
metadata:
  name: dwk-project-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dwk-project
  template:
    metadata:
      labels:
        app: dwk-project
    spec:
      volumes:
        - name: shared-vol
          persistentVolumeClaim:
            claimName: dwk-project-volume-claim
      containers:
        - name: dwk-project
          image: ethanrailo/dwk_project:version0.7
          volumeMounts:
            - name: shared-vol
              mountPath: /usr/src/app/files
          env:
            - name: PYTHONUNBUFFERED
              value: "1"
            - name: PORT
              value: "3000"
            - name: IN_CONTAINER
              value: "1"
