apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dwk-project-volume-claim
spec:
  storageClassName: project-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
