apiVersion: v1
kind: Service
metadata:
  name: dwk-project-frontend-svc
spec:
  type: ClusterIP
  selector:
    app: dwk-project-fe
  ports:
    - port: 2346
      protocol: TCP
      targetPort: 3000
