apiVersion: v1
kind: Secret
metadata:
    name: dwk-project-django-secret-key
    namespace: dwk-project
data:
    DJANGO_SECRET_KEY: ENC[AES256_GCM,data:MJ/ZP6WmR2FBoPPxZJ+pLrvtGjMJbLnSAw5rSbPdVCjtGhAnUdWk6PGXQSbKMQbfIBkzpd3+QlrQC0AlVeOZF3jAVYfNrcPvZ/GDy+rPoIEpGmtJgwrXLg4pJlc=,iv:o31h3EjKeIM91HDSlkUEGAmufssN3h0qw3J6Yt8Dg70=,tag:Xqg9ChjDCrgo/TwYvUiJ6A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age15tsyh0079tuszf6cxxfjzqpcnzyettjajkhttcvvsferkmkmeyuq7uad6x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvN1Q1Zm45TnJXaExHdTVm
            em5qcm9LNWZiODFqc2R4QmpISzRyL21MUHpjCjVjQjR2Tit4NERwTUpZZ0hwdDlT
            Qm1KS3VJck5UR3prbVk3eVhWejY5VTgKLS0tIG9pbnpMbytwNDFUYVBvM3hIbk5j
            Z1laRHBRRFdIYVZyZDBGWWkzREM4MjgKlHl/4JdaVb/+yPQsm2PXVb2vKJiOG9D2
            XbQD/6cdMa46TNKW6QHXULX8KkaveJUaTTR7O3urhR4p9V83kEespQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-06T09:01:30Z"
    mac: ENC[AES256_GCM,data:SvKmvj8harAFxkFMb1yZSqIaYDtJxyDSqdo6Di0e8jWe7eQG33OFjz7T70ZwuNVlNDYKqBYmj97jvidrwoXZCvjyybJ2av3yDStz7XeTxrBaH/sRu46ZXIbpoJKFqnOXEi2UsHYcti1zNfoT1cIgy86oT2vHItrmdPDm/qrKMok=,iv:dc8Vo8eRX6HbnvzN13ESxvsDl7PpYMVDkTSBSjH9B1k=,tag:NL11r7+qBWo3+miWeETGWg==,type:str]
    pgp: []
    encrypted_regex: ^(data)$
    version: 3.9.3
