apiVersion: batch/v1
kind: CronJob
metadata:
  namespace: dwk-project
  name: todo-creator
spec:
  schedule: "@hourly"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: todo-creator
              image: ethanrailo/todo-creator:version1.01
              env:
                - name: TODO_URL
                  value: "http://dwk-project-backend-svc.dwk-project:2348/todos/"
          restartPolicy: OnFailure
