apiVersion: v1
kind: PersistentVolume
metadata:
  name: dwk-project-pv
  namespace: dwk-project
spec:
  storageClassName: project-pv
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  local:
    path: /tmp/kube-project
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - k3d-k3s-default-agent-0
